# Token Type
# This enumerated type has not been tested
# I haven't been implementing it
class TokenType(object):
	# RESERVED WORDS
	MP_AND = 0
	MP_BEGIN = 1
	MP_DIV = 2
	MP_DO = 3
	MP_DOWNTO = 4
	MP_ELSE = 5
	MP_END = 6
	MP_FALSE = 7
	MP_FIXED = 8
	MP_FLOAT = 9
	MP_FOR = 10
	MP_FUNCTION = 11
	MP_IF = 12
	MP_INTEGER = 13
	MP_MOD = 14
	MP_NOT = 15
	MP_OR = 16
	MP_PROCEDURE = 17
	MP_PROGRAM = 18
	MP_READ = 19
	MP_REPEAT = 20
	MP_STRING = 21
	MP_THEN = 22
	MP_TRUE = 23
	MP_TO = 24
	MP_UNTIL = 25
	MP_VAR = 26
	MP_WHILE = 27
	MP_WRITE = 28
	MP_WRITELN = 29

	# IDENTIFIERS
	MP_IDENTIFIER = 30
	MP_INTEGER_LIT = 31
	MP_FIXED_LIT = 32
	MP_FLOAT_LIT = 33
	MP_STRING_LIT = 34

	# SINGLE STRING TOKENS
	MP_ASSIGN = 35
	MP_COLON = 36
	MP_COMMA = 37
	MP_EQUAL = 38
	MP_FLOAT_DIVIDE = 39
	MP_GEQUAL = 40
	MP_GTHAN = 41
	MP_LEQUAL = 42
	MP_LPAREN = 43
	MP_LTHAN = 44
	MP_MINUS = 45
	MP_NEQUAL = 46
	MP_PERIOD = 47
	MP_PLUS = 48
	MP_RPAREN = 49
	MP_SCOLON = 50
	MP_TIMES = 51

	# SPECIAL TOKENS
	MP_EOF = 62
	MP_RUN_COMMENT = 63
	MP_RUN_STRING = 64
	MP_ERROR = 65

	# UNDEFINED
	UNDEFINED = -1

